USE ORDER_DB;
INSERT INTO ORDER_TABLE (ORDER_ID, PRODUCT_NAME, BRAND, CUST_ID, CREATED) VALUES (1, 'LG TV', 'LG', 'CUS_145',  NOW());
INSERT INTO ORDER_TABLE (ORDER_ID, PRODUCT_NAME, BRAND, CUST_ID, CREATED) VALUES (2, 'Sony PS', 'SONY', 'CUS_231',  NOW());