CREATE DATABASE ORDER_DB;
USE ORDER_DB;
CREATE TABLE ORDER_TABLE
        (
        ORDER_ID INT(10) NOT NULL AUTO_INCREMENT,
        PRODUCT_NAME VARCHAR(100) NOT NULL,
        BRAND VARCHAR(50) NOT NULL,
        CUST_ID VARCHAR(50) NOT NULL,
        CREATED TIMESTAMP NOT NULL,
        PRIMARY KEY(ORDER_ID)
        );